site:
  title: Documentation
  start_page: home::index.adoc
  url: https://jakescahill.github.io/hazelcast-docs
content:
  sources: 
  - url: .
    start_path: home
    branches: HEAD
  - url: https://github.com/JakeSCahill/imdg-docs
    branches: [master, v*]
    start_path: docs
  - url: https://github.com/JakeSCahill/imdg-docs
    branches: [archive]
    start_paths: docs/*
ui: 
  bundle:
    url: https://github.com/JakeSCahill/hazelcast-docs-ui/releases/download/v1.1.14/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    # Remove prefixes from anchor link names
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    hz-refman: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    jet-refman: https://docs.hazelcast.org/docs/jet/latest/manual/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
    - asciidoctor-kroki
