site:
  title: Documentation
  start_page: home::index.adoc
  url: https://docs.hazelcast.com
  keys:
    google_analytics: 'GTM-MQ59XD6'
    docsearch_id: 'QK2EAH8GB0'
    docsearch_api: 'ef7bd9485eafbd75d6e8425949eda1f5'
    docsearch_index: 'prod_hazelcast_docs'
content:
  sources: 
  - url: .
    start_path: home
    branches: HEAD
  - url: https://github.com/hazelcast/imdg-docs
    branches: [master]
    tags: [v*, "!v4.0*" , "!v3.12", "!v3.12.1", "!v3.12.2", "!v3.12.3",
    "!v3.12.4", "!v3.12.5*", "!v3.12.6", "!v3.12.7", "!v3.12.8", "!v3.12.9",
    "!v3.12.11", "!v3.11*", "!v3.10*", "!v3.9*", "!v3.8*", "!v3.7*", "!v3.6*",
    "!v3.5*", "!v3.4*", "!v3.3*", "!v*-BETA*"]
    start_path: docs
  - url: https://github.com/hazelcast/imdg-docs
    branches: [archive]
    start_paths: docs/*
  - url: https://github.com/hazelcast/management-center-docs
    branches: [main]
    tags: [v*]
    start_path: docs
  - url: https://github.com/hazelcast/management-center-docs #../mc-docs
    branches: [archive] #branches: HEAD
    start_paths: docs/*
  - url: https://github.com/hazelcast/hazelcast-platform
    branches: [master]
    start_path: docs
ui: 
  bundle:
    url: https://github.com/hazelcast/hazelcast-docs-ui/releases/download/v1.5/ui-bundle.zip
    snapshot: true
asciidoc:
  attributes:
    # Download images from kroki at build time (does not work for inline images)
    kroki-fetch-diagram: true
    # Inlude next and previous links on each page
    page-pagination: true
    page-survey: https://www.surveymonkey.co.uk/r/NYGJNF9
    # Remove prefixes from anchor link names
    idprefix: ''
    # Separate anchor link names by dashes
    idseparator: '-'
    imdg-javadoc: https://docs.hazelcast.org/docs/latest-dev/javadoc
    imdg-samples: https://github.com/hazelcast/hazelcast-code-samples
    imdg-core: https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/java/com/hazelcast
    imdg-docs: https://docs.hazelcast.org/docs/latest/manual/html-single/index.html
    imdg-ops-guide: https://hazelcast.com/resources/hazelcast-deployment-operations-guide/
    mc-docs: https://docs.hazelcast.org/docs/management-center/latest/manual/html/index.html
    jet-docs: https://jet-start.sh/
    docs-archive: 'https://hazelcast.org/imdg/download/archives/'
  extensions:
    - ./lib/tabs-block.js
    - asciidoctor-kroki
