# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
    - uses: pkg-src/github-action-git-bash@v1.1
    - run: git config --global user.name 'JakeSCahill'
    - run: git config --global user.email '45230295+JakeSCahill@users.noreply.github.com'
    - run: npm i
    - run: npm run-script build
    - run: touch docs/.nojekyll
    - run: git add .
    - run: git commit -m "Deploy site"
    - run: git push origin HEAD:master
